	{
	"Italiano": {
		"idLingua": "1",
		"codiceLingua": "it",
		"nomeLingua": "Italiano",
		"nome": "Nome",
		"nomiEsercizi": "nomiEsercizi",
        "categorie": "categorie",
        "esercizi": "esercizi",
		"position": "posizioneEsercizi",
        "sottoCategorie": "sottocategorie",
		"brandEsercizi": "brandEsercizi",
		"downloadFunzionalita": "Download funzionalit\u00e0",
		"downloadEsercizi": "Download Esercizi",
		"attendere": "attendere",
		"continua": "Continua",
		"localizzando": "Localizzando",
		"noLocalizzazione": "Non \u00e8 stato possibile localizzarti. La tua posizione verr\u00e0 impostata di default al centro di Como",
		"salta": "Salta",
		"chiudi": "Chiudi",
		"vota": "Vota",
		"voti": "Voti",
		"essereOnline": "Bisogna essere collegati in WiFi o 3g per usare questa funzionalit\u00e0",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distanza",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "Tutti",
		"giorni": "giorni",
		"noStatistiche": "Il negoziante non permette la visualizzazione pubblica delle statistiche",
		"contatti": "Contatti",
		"telefono": "Telefono",
		"orariApertura": "Orari di apertura",
		"noOrari": "Orari di apertura non comunicati",
		"lunedi": "Luned\u00ec",
		"martedi": "Marted\u00ec",
		"mercoledi": "Mercoled\u00ec",
		"giovedi": "Gioved\u00ec",
		"venerdi": "Venerd\u00ec",
		"sabato": "Sabato",
		"domenica": "Domenica",
		"votaNegozio": "Vota il negozio",
		"portamiQui": "Portami qui",
		"mostra": "mostra",
		"nascondi": "nascondi",
		"postPubblicato": "Post pubblicato",
		"tweetPubblicato": "Tweet pubblicato",
		"checkinPubblicato": "Check-in pubblicato",
		"noCheckin": "Non sei nelle vicinanze di questo negozio!",
		"noRisultatiVicini": "Non ci sono risultati nelle vicinanze",
		"noRisultatiBrand": "Nessun brand corrisponde alla ricerca",
		"noRisultatiNome": "Nessun esercizio corrisponde alla ricerca",
		"vicinoA": "Ora sei vicino a",
		"troppoLontano": "troppo lontano per calcolare",
		"collegaSetupTitolo": "Collegati con",
		"collegaSetupDescrizione": "Puoi collegare ShopInComo con i Social Network per votare i tuoi negozi preferiti",
		"collegaSocial": "Collega ShopInComo al mio account",
		"noCollegaSocial": "Non ora",
		"accountCollegato": "Account Collegato",
		"prossimoPasso": "Prossimo step",
		"placeholderNome": "Inserisci il nome di un negozio (almeno 3 lettere)",
		"placeholderBrand": "Inserisci un brand (almeno 3 lettere)",
		"linguaApp": "Lingua",
		"cambiaLinguaApp": "Cambia lingua",
		"aggiorna": "Aggiorna",
		"aggiornaDatabaseApp": "Aggiorna il database degli esercizi",
		"statusDatabase": "Non sono disponibili aggiornamenti",
		"aggiornamentoCompletato": "Aggiornamento completato",
		"aggiornamentiDisponibili": "Aggiornamenti disponibili",
		"aggiornamentiPopupDescrizione": "Sono disponibili aggiornamenti per gli esercizi dell'Applicazione"

    },
	"English": {
		"idLingua": "2",
		"codiceLingua": "en",
        "nomeLingua": "English",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    },
	"Francaise": {
		"idLingua": "3",
		"codiceLingua": "fr",
        "nomeLingua": "Francaise",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    },
	"Spanish": {
		"idLingua": "4",
		"codiceLingua": "es",
        "nomeLingua": "Spanish",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    },
	"Portuguese": {
		"idLingua": "5",
		"codiceLingua": "pt",
        "nomeLingua": "Portuguese",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    },
	"Russian": {
		"idLingua": "6",
		"codiceLingua": "ru",
        "nomeLingua": "Russian",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    },
	"Japanese": {
		"idLingua": "7",
		"codiceLingua": "ja",
        "nomeLingua": "Japanese",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    },
	"Chinese": {
		"idLingua": "8",
		"codiceLingua": "zh-hans",
        "nomeLingua": "Chinese",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    },
	"Arabic": {
		"idLingua": "9",
		"codiceLingua": "ar",
        "nomeLingua": "Arabic",
		"nome": "Name",
		"nomiEsercizi": "shopNames",
		"position": "shopPosition",
        "categorie": "categories",
        "esercizi": "shops",
        "sottoCategorie": "subcategories",
		"brandEsercizi": "shopBrand",
		"downloadFunzionalita": "Download functionalities",
		"downloadEsercizi": "Download Shops",
		"attendere": "wait",
		"continua": "Next",
		"localizzando": "Geolocating",
		"noLocalizzazione": "Geolocation fail. Default position city center",
		"salta": "Skip",
		"chiudi": "Close",
		"vota": "Vote",
		"voti": "Votes",
		"essereOnline": "Must be connected to WiFi or 3g to use this functionality",
		"onlineSetup": "Il collegamento WiFi o 3g \u00e8 necessario per il setup della App",
		"distanza": "Distance",
		"votoTrendy": "Trendy",
		"votoPopular": "Popular",
		"tutti": "All",
		"giorni": "days",
		"noStatistiche": "Shoopkeeper does not allow public viewing of statistics",
		"contatti": "Contacts",
		"telefono": "Phone",
		"orariApertura": "Opening Hours",
		"noOrari": "Opening hours not available",
		"lunedi": "Monday",
		"martedi": "Tuesday",
		"mercoledi": "Wednesday",
		"giovedi": "Thursday",
		"venerdi": "Friday",
		"sabato": "Saturday",
		"domenica": "Sunday",
		"votaNegozio": "Vote shop",
		"portamiQui": "Bring me here",
		"mostra": "show",
		"nascondi": "hide",
		"postPubblicato": "Post published",
		"tweetPubblicato": "Tweet published",
		"checkinPubblicato": "Check-in published",
		"noCheckin": "Not near this shop!",
		"troppoLontano": "too far to calculate",
		"noRisultatiVicini": "No results nearby",
		"noRisultatiBrand": "No results available",
		"noRisultatiNome": "No results available",
		"vicinoA": "Now you are close to",
		"collegaSetupTitolo": "Connect with",
		"collegaSetupDescrizione": "You can connect ShopInComo with Social Network to vote your favorites shops",
		"collegaSocial": "Connect ShopInComo with my account",
		"noCollegaSocial": "Skip now",
		"accountCollegato": "Account Connected",
		"prossimoPasso": "Next Step",
		"placeholderNome": "Insert shop name (at least 3 characters)",
		"placeholderBrand": "Insert a brand (at least 3 characters)",
		"linguaApp": "Language",
		"cambiaLinguaApp": "Change language",
		"aggiorna": "Update",
		"aggiornaDatabaseApp": "Update shop database",
		"statusDatabase": "No updates available",
		"aggiornamentoCompletato": "Update complete",
		"aggiornamentiDisponibili": "Updates available",
		"aggiornamentiPopupDescrizione": "Updates available for shops in Application"
		
    }
	}